package org.javainaction.recursion;

import java.util.ArrayList;
import java.util.List;

/**
 * Given a word, write a function to generate all of its unique generalized abbreviations.
 *
 * Generalized abbreviation of a word can be generated by replacing each substring of the word by the count of
 * characters in the substring. Take the example of “ab” which has four substrings: “”, “a”, “b”, and “ab”.
 * After replacing these substrings in the actual word by the count of characters we get all the generalized
 * abbreviations: “ab”, “1b”, “a1”, and “2”.
 *
 * Example 1:
 *
 * Input: "BAT"
 * Output: "BAT", "BA1", "B1T", "B2", "1AT", "1A1", "2T", "3"
 * Example 2:
 *
 * Input: "code"
 * Output: "code", "cod1", "co1e", "co2", "c1de", "c1d1", "c2e", "c3", "1ode", "1od1", "1o1e", "1o2",
 * "2de", "2d1", "3e", "4"
 * @see GenerateDivTags
 * @see GenerateParenthesesRecursive
 */
public class GeneralizedAbbreviationRecursive {
    public static List<String> generateGeneralizedAbbreviation(String word) {
        List<String> result = new ArrayList<>();
        generateAbbreviationRecursive(word, new StringBuilder(), 0, 0, result);
        return result;
    }

    private static void generateAbbreviationRecursive(String word, StringBuilder current, int position, int count,
                                                      List<String> result) {

        if (position == word.length()) {
            //suffix
            if (count != 0) current.append(count);

            result.add(current.toString());
        } else {
            // continue abbreviating by incrementing the current abbreviation count
            // here we do not abbreviate, current string, cnt + 1, pos + 1
            generateAbbreviationRecursive(word, new StringBuilder(current), position + 1,
                    count + 1, result);

            // restart abbreviating, append the count and the current character to the string
            // here we abbreviate, update current string, cnt = 0, pos + 1

            //prefix
            StringBuilder currentNew = new StringBuilder();
            if (count != 0)  currentNew.append(count);

            generateAbbreviationRecursive(word, currentNew.append(word.charAt(position)), position + 1,
                    0, result);
        }
    }

    public static void main(String[] args) {
        System.out.println("Generalized abbreviation are: " + generateGeneralizedAbbreviation("BAT"));

        System.out.println("Generalized abbreviation are: " + generateGeneralizedAbbreviation("code"));
    }
}
